version: "3.8"

services:
  app:
    hostname: "app"
    build:
      args:
        - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=development
    ports:
      - "3355:3355"
    volumes:
      - ./src:/var/www/src
      - ./uploads:/var/www/uploads
    command: npm run dev
